### ISSUE TITLE
Missing signatures and voting power inside block

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#125] opened 2021-05-04 13:14 UTC
Since the new update bdjuno no longer keeps the history of certain things inside the block details page

- Signatures (who signed and who didn't sign the block at that block)
- The voting power % at that block

![image](https://user-images.githubusercontent.com/42913823/117008231-1604c400-ad1d-11eb-81e7-71fdcd0be0e1.png)

Pros:
The current setup definitely saves a lot more space and is more efficient. 

Cons:
The current Bdjuno setup will be unable to display the 2 details mentioned about

@kwunyeung @RiccardoM 
Let me know how you guys would like to move forward with this. (Keep in mind of the timeline)

**Comment by rmontagnin** [comment] 2021-05-05 05:19
I can implement those back easily. They shouldn't take much space on the database

**Comment by ryuash** [comment] 2021-05-05 06:38
Sure let's add the history back for validator voting power

**Comment by rmontagnin** [comment] 2021-05-06 06:40
@ryuash Could you please tell me the queries you used to run to get these data?

**Comment by ryuash** [comment] 2021-05-06 06:41
Query the validator status by height and get all the validators active during that block. Cross check if they were in precommits. Similar situation with the voting power % of that height.
```
query BlockDetails($height: bigint) {
  transaction(where: {height: {_eq: $height}}) {
    height
    hash
    messages
    success
  }
  pool: staking_pool(limit: 1, where: {height: {_eq: $height}}) {
    bondedTokens: bonded_tokens
  }
  block(limit: 1, where: {height: {_eq: $height}}) {
    height
    hash
    timestamp
    txs: num_txs
    validator {
      validatorInfo: validator_info {
        operatorAddress: operator_address
      }
    }
    preCommitsAggregate: pre_commits_aggregate{
      aggregate{
        sum {
          votingPower: voting_power
        }
      }
    }
  }
  preCommits: pre_commit(where: {height: {_eq: $height}}) {
    validator {
      validatorInfo: validator_info {
        operatorAddress: operator_address
      }
    }
  }
  validatorStatus: validator_status(where: {height: {_eq: $height}, status: {_eq: 3}}) {
    validator {
      validatorVotingPowers: validator_voting_powers(limit: 1, where: {height: {_eq: $height}}) {
        votingPower: voting_power
      }
      validatorInfo: validator_info {
        operatorAddress: operator_address
      }
    }
  }
}
```

**Comment by rmontagnin** [comment] 2021-05-13 07:30
@ryuash Re-implementing the history of voting powers and statues would mean making the database increase exponentially at each block. Is this really necessary to show to the users? To be honest, I've never heard of anyone wanting to know the sum of all the voting powers of validators that signed a block. If this is not strictly necessary, I would suggest to delete that detail from the block page.

**Comment by ryuash** [comment] 2021-05-13 07:36
@kwunyeung @RiccardoM up to you. I listed the pros and cons above

**Comment by rmontagnin** [comment] 2021-05-13 07:40
@kwunyeung @ryuash Final note: signatures have been re-implemented and you should be able to display who signed a block and who didn't. 

Only the voting power at that particular block will be removed. 

```graphql
query Signatures {
  block(where:{height:{_eq:224407}}) {
    height    
    pre_commits {
      validator_address
    }
  }
}
```

**Comment by kwunyeung** [comment] 2021-05-13 08:09
@RiccardoM can the total signed voting power be aggregated when indexing the block signatures? The total signed voting power is reference on "whether the block has high votes". Although in BFT, we only consider if consensus is made or not, this figure may give us some other interesting implications.

**Comment by rmontagnin** [comment] 2021-05-13 08:15
> @RiccardoM can the total signed voting power be aggregated when indexing the block signatures? The total signed voting power is reference on "whether the block has high votes". Although in BFT, we only consider if consensus is made or not, this figure may give us some other interesting implications.

Actually, I've taken a look at this and currently Tendermint does not include current block's signature inside the block itself. Signatures for block `X` are included inside block `X+1`. This means that if someone opens the details of block `X` when it's added to the chain, they won't be able to see the voting power using the signatures until block `X+1` is created and added to the chain as well. 

Aside from this, I honestly see no reason in showing such a detail to the user. Suppose for example that a block has low voting power associated to it. What does this tell us? Probably not much, as it might be due to the fact that some validators missed that block. But that doesn't tell us why they missed, it might have been just one block.

**Comment by kwunyeung** [comment] 2021-05-13 08:36
@RiccardoM yes the signatures, or the proof, of `X` is always in `X+1` and this is how the legacy Big Dipper is showing. If we don't see a signature of validator `V` at block height `X+1`, we would say `V` is missing at `X` but not `X+1` as this only means `V` was offline when block `X` was being committed on chain. I agree showing it at a certain block may not give many information. My point is when we have this data and analysing in a longer term, it may give another picture in some interesting perspective that we do not know at this moment. It doesn't have to be done right now if this is too complicated to achieve but having such aggregating data will let us see more things in different perspective for sure. This can be added in the future when we wanna have a better analysis on the chain.

@ryuash talking about the signatures, in the legacy Big Dipper, I actually show the validator is missing the previous block but not at the block with the signature.

**Comment by rmontagnin** [comment] 2021-05-13 08:57
@kwunyeung Currently, all the signatures are stored inside the database since they do not weight that much. The problem is showing the voting power associated with such signatures at a given height. This would mean storing the history of **all** voting powers of **all** validators at **any** block, which would cause the database size to increase exponentially (ie. storing 150 voting powers per block, if we have 150 active validators signing each block). That's the problem, not storing the signatures.

**Comment by kwunyeung** [comment] 2021-05-13 09:01
@RiccardoM I know. I understand that and this is not we wanna achieve in the first place. We would like to show the total signed voting power of a block which is just a number in the database. If you can do the sum of the signed voting power when storing the blocks, we will have that value for each block.

**Comment by rmontagnin** [comment] 2021-05-13 10:10
@kwunyeung I've just checked the database, and I currently store the voting power for each of the signatures of a block. This should allow to get the signed voting power using the given query @ryuash: 

```graphql
query SignedVotingPower {
  block(where:{height:{_eq:224407}}) {
    pre_commits_aggregate {
      aggregate {
        sum {
          voting_power
        }
      }
    }
  }
}
```

<details>

<summary>Example</summary>

```json
{
  "data": {
    "block": [
      {
        "pre_commits_aggregate": {
          "aggregate": {
            "sum": {
              "voting_power": 2166115
            }
          }
        }
      }
    ]
  }
}
```

</details>

If you are fine with only signed voting power (and not online/offline) this should be sufficient. 

@ryuash Please note that since this is updated only at height `X+1`, considering block `X` you might get `0` initially and then once block `X+1` is created you get the real value.

**Closed as completed** 2021-05-13 10:21 UTC
Labels: Type: Enhancement, Status: WIP
