### ISSUE TITLE
User staking not updated correctly

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#269] opened 2021-11-22 04:51 UTC
User redelegates from validator A to validator B. Before redelegation is complete, User undelegates from validator B. 

Bdjuno now stores both redelegation and unbonding.

Expectation:
Redelegation is removed and only Unbonding remains;
Any staking TX should update the user's staking info

**Comment by rmontagnin** [comment] 2021-11-22 09:24
@ryuash I don't think this is a bug with BDJuno, but is how things should work. This is because the user **cannot** undelegate before the redelegation is completed. What I believe happened here is the following: 

- the user had an amount of tokens delegated (let's say `100 DSM` for simplicity)
- they had parts of their tokens delegated to Validator A and part delegated to Validator B (let's say `20 DSM` to Val A and `80 DSM` to Val B) 
- the redelegated their amount from Val A to Val B (`20 DSM`)
- they unbonded their already-delegated amount from Val B (part of the `80 DSM`)

I believe this is the case because inside Cosmos you **can not** undelegate some tokens before they are fully re-delegated to the destination validator

**Comment by rmontagnin** [comment] 2021-11-24 06:12
After investigating more, turns out this is not a bug but how things are intended to work. As we can see, the redelegation and unbonding delegation exist at the same time on-chain as well: 
- [Redelegations](https://api.mainnet.desmos.network/cosmos/staking/v1beta1/delegators/desmos1rzhewpmmdl72lhnxj6zmxr4v94f522s4ff2psv/redelegations)
 - [Unbonding delegations](https://api.mainnet.desmos.network/cosmos/staking/v1beta1/delegators/desmos1rzhewpmmdl72lhnxj6zmxr4v94f522s4ff2psv/unbonding_delegations)

I'm going to close this issue and consider it a non bug

**Closed as completed by rmontagnin** 2021-11-24 06:12 UTC
Labels: Cat: x/staking
